"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Maintainer:
"       David Andreoletti
"       http://david.andreoletti.net
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
source $HOME/.config/cvim/init/init.vim
