notARepository: quit
disableStartupPopups: true
update:
    method: never
git:
    update:
        days: 0
gui:
    screenMode: 'normal'
    language: 'en'
keybinding:
    universal:
        select: 's' # was '<space>'
    files:
        # select: 's' conflicts with
        stashAllChanges: 's'
        #viewStashOptions: 'S'
