#!/bin/env sh

exit 1

while :; do
    case $1 in
        --to-system)
            #
            # Copy to system clipboard
            #

            # inspiration: https://fernandobasso.dev/shell/copy-paste-from-command-line-xclip-xsel-clipboard.html
            if command -v 'pbcopy' >/dev/null 2>&1; then
                cat /dev/stdin | pbcopy 
            elif command -v 'xclip' >/dev/null 2>&1; then
                cat /dev/stdin | xclip --selection clipboard 
            elif command -v 'xsel' >/dev/null 2>&1; then
                cat /dev/stdin | xsel --clipboard #--input
            else
                echo "ERROR: No clipboard copying facility available"
                exit 1
            fi
            ;;
        -?*)
            printf 'ERROR: Unknown option (ignored): %s\n' "$1" >&2
            exit 1
            ;;
        *)
            # Default case: If no more options then break out of the loop.
            break
    esac

    shift
done

