_NEOVIM_PYENV_VIRTUALENV_VERSION="3.11.7"
_NEOVIM_PYENV_VIRTUALENV_NAME="neovim_py311"
export _NEOVIM_PYENV_PYTHON_PATH="$HOME/.pyenv/versions/${_NEOVIM_PYENV_VIRTUALENV_VERSION}/envs/${_NEOVIM_PYENV_VIRTUALENV_NAME}"
