_NEOVIM_PYENV_VIRTUALENV_VERSION="3.13.9"
_NEOVIM_PYENV_VIRTUALENV_NAME="neovim_py313"
export _NEOVIM_PYENV_PYTHON_PATH="$HOME/.pyenv/versions/${_NEOVIM_PYENV_VIRTUALENV_VERSION}/envs/${_NEOVIM_PYENV_VIRTUALENV_NAME}"
