[general]
# Auto reload config when changed
live_config_reload = true

#https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/terminal_app.toml"
]

[window]
startup_mode = "Maximized"
dynamic_title = true
decorations = "Full"

[scrolling]
history = 100000
multiplier = 3

[cursor]
thickness = 1

[cursor.style]
shape = "Beam"
blinking = "Off"

[font]
size = 14

[[hints.enabled]]
# This requires an absolute path to work, until if ever, $HOME is supported: https://github.com/alacritty/alacritty/issues/7743#event-11836817470
# NOT SUPPORTED: command = { program = "bash", args = [ "$HOME/.bin/opener" ] } 
# NOT SUPPORTED: ommand = { program = "$HOME/.bin/openner" } 
command = { program = "bash", args = [ "/absolute/path/to/dotfiles/.bin/opener" ] } 

hyperlinks = true
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[debug]
persistent_logging = false
log_level = "Warn"

#render_timer = true
