#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote="$1"
url="$2"

IFS=' '
GIT_DEFAULT_HOOKS_DIR="$HOME/.config/git/hooks"
while read local_ref local_sha remote_ref remote_sha
do
	[ -r "$GIT_DEFAULT_HOOKS_DIR/pre-push.fortune.sh" ] && $GIT_DEFAULT_HOOKS_DIR/pre-push.fortune.sh $local_ref $local_sha $remote_ref $remote_sha || exit 1
done

